### PR TITLE
Courtney

### PR DESCRIPTION
**Pull request by clburns107**

### CODE REVIEW

**Comment by clburns107** [comment]
Im not sure how to do a loop in on these pages... i need a way to loop through all of my posts to display them as links.

**Comment by halfghaninne** [comment]
Looks like there are a couple of places where your theme loops through some collection in order to display it: 
- https://github.com/clburns107/clburns107.github.io/blob/master/_includes/header.html#L13-L17
- https://github.com/clburns107/clburns107.github.io/blob/master/_includes/footer.html#L4-L14

I'd expect that looping through posts would work similarly. Please let me know if that points you in a helpful direction.

**Comment by clburns107** [comment]
Sorry i guess i should have been clearer.  I did see where there looks to be some sort of loop in the header.  Which i have deduced will make another links in the menu navigation bar. However i can't tell how the loops works and therefore how to manipulate it so that it is looping through the files in _site/2016.   and if i can get it to loop through _site/2016 how do i then get it to link to those pages?

more specifically how do i find out what the variables in the loop are and where can i change those at? since its not ruby code what is it? and where does it live?
{% for my_page in site.pages %}
            {% if my_page.title %}
            <li><a href="{{ my_page.url | prepend: site.baseurl }}">{{ my_page.title }}</a></li>
            {% endif %}
            {% endfor %}

**Comment by sumeetjain** [comment]
I'm not 100% sure either, but you can check https://jekyllrb.com/docs/home/ for documentation. This is one reason why I recommended finding a theme that already matches your content architecture; so if this is becoming a time-suck, consider choosing a different theme.

**Comment by clburns107** [comment]
[](url)

**Pull request closed without merging**
